import 'dart:ui';

class Player {
  final String name;
  final Color color;

  Player(this.name, this.color);

  static const List<String> names = [
    "Acey",
    "Birdie",
    "Chainz",
    "Sexy Boy",
    "Heißer",
    "Zippy",
    "Annie",
    "Bogey",
    "Dashy",
    "Eagle",
    "Vader",
    "Puta",
    "Ivy",
    "Kween",
    "Mando",
    "Emilch",
    "Queenie",
    "Rollala",
    "Sassy",
    "Twirly",
    "Upsy",
    "Wanda",
    "Xtra",
    "Bogaloo",
    "Tschoggla",
    "Fayda",
    "Groovy",
    "Hooker",
    "Kiki",
    "Throwa",
    "HoopHoop",
    "Whirly",
    "BamBam",
    "Hoopy",
    "Icy",
    "Karma",
    "Quixie",
    "RollaRuh",
    "LagLord",
    "Tricky",
    "Uno",
    "NoobSlaya",
    "Wiggy",
    "PingPong",
    "Cheeseruh",
    "OopsHeadshot",
    "Bubbles",
    "PotatoAim",
    "MilkSniper",
    "Flippa",
    "Player69",
    "BananaShot",
    "DisQ",
    "Kitty",
    "404Skillz",
    "Momo",
    "Ninja",
    "Oreo",
    "Squeezer",
  ];
}